# Generated by Django 5.2.2 on 2025-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estadios/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='equipos_favoritos',
            field=models.ManyToManyField(blank=True, to='partidos.equipo'),
        ),
        migrations.AlterField(
            model_name='eventopartido',
            name='tipo',
            field=models.CharField(choices=[('GOL', 'Gol'), ('AMARILLA', 'Tarjeta amarilla'), ('ROJA', 'Tarjeta roja'), ('CAMBIO', 'Cambio'), ('LESION', 'Lesión')], max_length=10),
        ),
    ]
